#ifndef CONSTANTS_H_
#define CONSTANTS_H_

//#define USE_DEV_SQUARES
#define USE_DS_STYLE

#define FPS_TARGET 60
#define FIRST_LEVEL 1
#define INITIAL_SECONDS 10

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 792

#define AREA_WIDTH 800
#define AREA_HEIGHT 600

#define EXCESSIVE_DISTANCE 640000
#define TARGET_HEIGHT 100
#define TARGET_MINIMUM_DISTANCE 2500
#define HIGHEST_TEXTURE_INDEX 1

#define BOUNCE_OFFSET 2
#define BASE_SPEED 1.5f
#define BASE_SIN_AMPLITUDE 1

#define CLICK_RANGE 6000

#define ALARMFLAG_COUNT 11
#define BGM_TRACK_COUNT 7
#define POINTS_SFX_COUNT 4

// times are given in seconds
#define PREROUND_ALARM_DURATION 1
#define DRUMROLL_ALARM_DURATION 0
#define TARGET_MISSED_ALARM_DURATION 1
#define TARGET_HIGHLIGHT_DURATION 2
#define ROUND_BUFFER_DURATION 2
#define SCORE_COUNTUP_DURATION 1
#define LOSE_TIMER_DURATION 4

#define EXAMPLE_STRING "Example String"

#endif
